app.name=VadalogParallel
server.port=8080

# spring log levels
logging.level.org.springframework=WARN
logging.level.org.springframework.web=WARN
logging.level.org.apache.catalina=WARN

server.error.include-message=always
management.endpoint.health.show-details=always

spring.banner.charset=UTF-8 # Banner file encoding.
spring.banner.location=classpath:/usr/local/lib/banner.txt # Banner text resource location.
#spring.main.banner-mode=console # Mode used to display the banner when the application runs.

# set the logging level here
logging.level.root=info

logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n
logging.pattern.file=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n
logging.file.name=./log/prometheux.log