spark.app.name prometheux-livy
## [OPTIONS] local[*], local[Number_of_cores], 
## spark://HOST:PORT, yarn 
spark.master local[*]
## max memory for driver
spark.driver.memory 4g
## max memory per executor
spark.executor.memory 4g
## number of executor per instance of each worker
spark.executor.instances 1
## number of cores on each executor
spark.executor.cores 4
## allocates dynamically instances and cores
spark.dynamicAllocation.enabled false
## autotune the shuffle partition number
spark.sql.adaptive.enabled true
## the number of partitions to use when shuffling data for joins or aggregations
## if run in local[*] mode set this number as the number of your machine's core
## if run in yarn mode set this number as the number of machine * number of cores of each machine
spark.sql.shuffle.partitions 4
## directory to use for scratch space
spark.local.dir tmp
## Whether to compress RDD checkpoints
spark.checkpoint.compress true
## Whether to compress before shuffling
spark.shuffle.compress true
## Set this property to -1 to use SortMergeJoin instead of Broadcast Hash Join
## spark.sql.autoBroadcastJoinThreshold=-1