property.filename=Default
property.version=0.1
testKey=testValue
sparkConfFile=spark-defaults.conf
## storage level for dataset persistence
persistanceStorageLevel=memoryOnly
## full path to spark rapids configurations file
sparkRapidsConfFile=spark-rapids.conf
## whether to select the preferred compute accelerator: cpu or gpu
computeAcceleratorPreference=cpu
## for livy rest service set this property to restService=livy (not availabe for academic license)
restService=off
repository.path=repository
nullGenerationMode=UNIQUE_NULLS
breakLineageStrategy=recreate

